# See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - ci
      - dependencies

  # TODO: Enable when the future Dockerfiles lands in the repository
  # Maintain dependencies for Docker files
  # - package-ecosystem: "docker"
  #   directory: "/docker"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - docker
  #     - dependencies

  # Maintain dependencies for legacy
  - package-ecosystem: "composer"
    directory: "/legacy"
    schedule:
      interval: "daily"
    labels:
      - php
      - dependencies

  # Maintain dependencies for Python apps
  - package-ecosystem: "pip"
    directory: "/analyzer"
    schedule:
      interval: "daily"
    labels:
      - python
      - dependencies

  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "daily"
    labels:
      - python
      - dependencies

  - package-ecosystem: "pip"
    directory: "/api_client"
    schedule:
      interval: "daily"
    labels:
      - python
      - dependencies

  - package-ecosystem: "pip"
    directory: "/playout"
    schedule:
      interval: "daily"
    labels:
      - python
      - dependencies

  - package-ecosystem: "pip"
    directory: "/shared"
    schedule:
      interval: "daily"
    labels:
      - python
      - dependencies

  - package-ecosystem: "pip"
    directory: "/worker"
    schedule:
      interval: "daily"
    labels:
      - python
      - dependencies

  # Maintain dependencies for NPM packages
  # - package-ecosystem: "npm"
  #   directory: "/ui"
  #   schedule:
  #     interval: "daily"
  #   labels:
  #     - javascript
  #     - dependencies

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
    labels:
      - javascript
      - dependencies
