# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale (5 months)
daysUntilStale: 150

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed. (1 month)
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 30

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - pinned
  - security
  - "[Status] Maybe Later"
  - "3.0-release-blocker"

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: false

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: true

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  activity in the last 5 months. It will be closed if no activity occurs in
  the next month.

  Please chat to us on [discourse](https://discourse.libretime.org/) or
  ask for help on our [chat](https://chat.libretime.org/) if you have any
  questions or need further support with getting this issue resolved.

  You may also label an issue as *pinned* if you would like to make sure
  that it does not get closed by this bot.

# Comment to post when removing the stale label.
# unmarkComment: >
#   Your comment here.

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This issue has been autmatically closed after is was marked as stale and
  did not receive any further inputs.

  Feel free to let us know on [discourse](https://discourse.libretime.org/) or
  ask for help on our [chat](https://chat.libretime.org/) if you feel this
  issue should not have been closed.

  Thank you for your contributions.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30
