site_name: LibreTime
theme: readthedocs

dev_addr: '0.0.0.0:8888'
site_dir: 'build/docs'
markdown_extensions:
- codehilite:
    noclasses: True
    pygments_style: emacs

repo_url: https://github.com/LibreTime/libretime/

extra_css:
  - '_css/term.css'

pages:
  - 'Home': index.md
  - 'What is LibreTime?': manual/index.md
  - 'Features': features.md
  - 'F.A.Q.': faq.md
  - 'Rights and Royalties': manual/rights-and-royalties/index.md
  - 'Using LibreTime':
    - 'On Air in 60 seconds!': 'manual/on-air-in-60-seconds/index.md'
    - 'Getting Started': manual/getting-started/index.md
  - 'The Settings Menu':
    - 'General': manual/preferences/index.md
    - 'Users': manual/users/index.md
    - 'Media Folders': manual/media-folders/index.md
    - 'Streams': manual/stream-settings/index.md
    - 'Support Feedback': manual/support-feedback/index.md
    - 'Status': manual/status/index.md
  - 'The Main Menus':
    - 'Now Playing': manual/now-playing/index.md
    - 'Add Media': manual/add-media/index.md
    - 'Library': manual/library/index.md
    - 'Calendar': manual/calendar/index.md
    - 'History': manual/history/index.md
    - 'Listen': manual/listen/index.md
    - 'Analytics': manual/listener-stats/index.md
    - 'Help': manual/help/index.md
  - 'LibreTime in the Studio':
    - 'Preparing Media for Ingest': manual/preparing-media-for-ingest/index.md
    - 'Live Shows with Mixxx': manual/live-shows-with-mixxx/index.md
    - 'Smartphone Journalism': manual/smartphone-journalism/index.md
    - 'Icecast and SHOUTcast': manual/icecast-and-shoutcast/index.md
    - 'Recording Shows': manual/recording-shows/index.md
  - 'Installation':
    - 'Install': install.md
    - 'Preparing the Server': manual/preparing-the-server/index.md
    - 'Setting the Server Time': manual/setting-the-server-time/index.md
  - 'Administration':
    - 'The airtime-log Command': manual/the-airtime-log-command/index.md
    - 'Backing Up the Server': manual/backing-up-the-server/index.md
    - 'Upgrading': manual/upgrading/index.md
    - 'Troubleshooting': manual/troubleshooting/index.md
    - 'Using Monit': manual/using-monit/index.md
  - 'Advanced Configuration':
    - 'Automated File Import': manual/automated-file-import/index.md
    - 'Icecast Handover': manual/icecast-handover/index.md
    - 'Promoting Your Station': manual/promoting-your-station/index.md
    - 'Stream Player for Your Website': manual/stream-player-for-your-website/index.md
    - 'Exporting the Schedule': manual/exporting-the-schedule/index.md
    - 'Interface Customization': manual/interface-customization/index.md
    - 'Interface Localization': manual/interface-localization/index.md
    - 'Host Configuration': manual/host-configuration/index.md
    - 'LibreTime API Authentication': manual/airtime-api-authentication/index.md
    - 'Secure Login with SSL or TLS': manual/secure-login-with-ssl/index.md
    - 'Icecast Statistics with Piwik': manual/icecast-statistics-with-piwik/index.md
    - 'FreeIPA Authentication': freeipa.md
  - 'Development':
    - 'Testing': testing.md
    - 'Database': database.md
    - 'Vagrant': vagrant.md
    - 'Translating': translating.md
    - 'Documentation': documentation.md
  - 'Appendix':
    - 'HD Audio Models': manual/hd-audio-models/index.md
    - 'About This Manual': manual/about-this-manual/index.md
