[tool.pylint.messages_control]
extension-pkg-whitelist = "pydantic"
disable = [
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
