name: API schema

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    if: github.repository_owner == 'libretime'
    name: Generate

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Clone api-client repo
        uses: actions/checkout@v3
        with:
          repository: "${{ github.repository_owner }}/api-client"
          path: api-client-repo
          ssh-key: "${{ secrets.API_CLIENT_DEPLOY_KEY }}"

      - name: Generate schema
        run: |
          make schema
          cp schema.yml ../api-client-repo/schema.yml
        working-directory: api

      - name: Push schema changes to API clients
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update schema for ${{ github.repository }}@${{ github.sha }}"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          repository: ./api-client-repo
